steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=BUILDPLATFORM=linux/amd64'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'
substitutions:
  _IMAGE: 'us-docker.pkg.dev/${PROJECT_ID}/backend/iam:latest'
