FROM node:18.19.0 AS front
WORKDIR /web
COPY ./web/package.json ./web/pnpm-lock.yaml ./web/.npmrc ./
RUN corepack enable && pnpm install --frozen-lockfile
COPY ./web .
RUN NODE_OPTIONS="--max-old-space-size=4096" CI=false pnpm run build

FROM golang:1.26 AS back
WORKDIR /go/src/hanzo-iam
ARG GITHUB_TOKEN
ENV GOPRIVATE=github.com/hanzoai/*,github.com/luxfi/*
RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o server .

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
COPY --from=back /go/src/hanzo-iam/server /server
COPY --from=front /web/build /web/build
EXPOSE 8000
ENTRYPOINT ["/server"]
