name: hanzo-iam
services:
  - name: iam
    source_dir: /
    github:
      repo: hanzoai/iam-v2
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    envs:
      - key: HTTP_PORT
        value: "8000"
        type: GENERAL