// Code generated by zipdoc; DO NOT EDIT.

package bootstrap

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("POST /v1/iam/admin/applications/upsert", zip.Doc{
		Description: "Creates an application or updates it in place, so a\ndeployment can declare the applications it needs and run the same declaration\non every environment and on every redeploy.\n\nIt says which of the two it did. Leave the client secret out and the existing\none is kept — so re-running your deployment does not rotate a credential your\nrunning services are holding.",
		Fields: map[string]string{
			"registration.enableCodeSignin": "EnableCodeSignin offers sign-in by an emailed or texted one-time code\nbeside the password. A POINTER for the same reason as IsShared: a plain\nbool reads as false on every reconcile that says nothing and would switch\nthe method off for every app whose caller never mentioned it.",
			"registration.expireInHours":    "ExpireInHours and RefreshExpireInHours are the application's token\nlifetimes. They are the ONLY declarative way to say that a refresh token\nmust OUTLIVE its access token: with neither stated, oidc.refreshTTL clamps\nthe refresh lifetime to the access lifetime, so the refresh_token grant the\nregistration advertises expires at the same instant as the token it was\nmeant to renew and can never be exercised. `hanzo-cli` sat in exactly that\nstate — a browser re-login every hour, and a live refresh returning 401.\n\nPOINTERS, for the same reason as IsShared: a plain float would read as 0 on\nevery reconcile that says nothing and reset a deliberate lifetime back to\nthe default. Nil means \"not stated, leave it\".",
			"registration.isShared":         "IsShared declares that this application serves EVERY organization, not only\nthe one named in Organization. It is the honest description of a brand app —\nhanzo-id, hanzo-chat, a brand console — whose customers each live in their own\ntenant: self-service onboarding moves a founder OUT of the brand org, so\n`user.Owner != app.Organization` is the steady state and the app really does\nserve every org. Application.ServesOrg reads it as one of the three ways to\nsay yes.\n\nA POINTER because omission must PRESERVE. This upsert is the operator's\nsteady-state reconcile and most callers say nothing about sharing; a plain\nbool would read as false on every one of them and silently un-share an app —\nthe same shape of accident that de-secreted apps through update-application.\nNil means \"not stated, leave it\"; only an explicit true or false moves it.",
			"registration.public":           "Public declares a client that CANNOT hold a credential — a browser SPA,\na CLI, a desktop app. It proves itself with PKCE instead, and the token\nendpoint treats \"no stored secret\" as exactly that (token.go: a secret is\nverified only when one is stored). Without this flag every upsert minted\na secret, so a public client could never be registered at all and its\nbrowser code->token exchange 401'd `invalid_client` forever.",
		},
	})
	zip.Describe("POST /v1/iam/admin/users/upsert", zip.Doc{
		Description: "Creates a person or updates them in place, so a deployment can\ndeclare the accounts it needs and re-run that declaration safely.\n\nIt converges the accounts it created and no others: `type` is the class the\ndeclaration gives a row, stamped on create and required to match on update, so\nan account that entered this store some other way is answered rather than\nadopted. Their organization must exist — a person's org is their tenancy, and a\nrow under one that does not is a principal no tenant contains.\n\nPasswords are hashed before they are stored. Leave the password out and their\ncurrent one is kept, so a redeploy never locks somebody out; send the same one\nagain and it is kept too, so a steady-state re-run is not a rotation.",
		Fields: map[string]string{
			"person.type": "Type is the identity CLASS the declaration gives this row — what KIND of\nprincipal it is: schema.Owner for the org's one human superuser,\nschema.ServiceAccount for a machine. It is the fact that scopes a converge to\nits OWN accounts: the create path stamps it, the update path requires the\nstored row to carry the same one, and no other surface writes either word (a\nperson who signs up is stamped \"normal-user\" by the create path they reach).\nSo a declaration converges the rows it made and refuses every other, and an\nexisting row's class is never re-written into a different kind of principal.",
		},
	})
}
