// Code generated by zipdoc; DO NOT EDIT.

package bootstrap

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("POST /v1/iam/admin/applications/upsert", zip.Doc{
		Description: "Creates an application or updates it in place, so a\ndeployment can declare the applications it needs and run the same declaration\non every environment and on every redeploy.\n\nIt says which of the two it did. Leave the client secret out and the existing\none is kept — so re-running your deployment does not rotate a credential your\nrunning services are holding.",
	})
	zip.Describe("POST /v1/iam/admin/users/upsert", zip.Doc{
		Description: "Creates a person or updates them in place, so a deployment can\ndeclare the accounts it needs and re-run that declaration safely.\n\nPasswords are hashed before they are stored. Leave the password out and their\ncurrent one is kept, so a redeploy never locks somebody out.",
	})
}
