// Code generated by zipdoc; DO NOT EDIT.

package certs

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/iam/certs", zip.Doc{
		Description: "Returns your organization's signing certificates, newest first — the keys\nthe tokens your applications verify are signed with. Private key material is\nmasked.\n\nYou see your own organization's certificates and no one else's; which\norganization that is comes from your credentials, not from the request, so a\nquery parameter can never widen the listing.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Cert].id": "Persisted fields",
		},
	})
	zip.Describe("GET /v1/iam/certs/get", zip.Doc{
		Description: "Returns one signing certificate — its algorithm, its validity window and\nits public half. The private key is masked.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Cert].id": "Persisted fields",
		},
	})
	zip.Describe("POST /v1/iam/certs", zip.Doc{
		Description: "Adds a signing certificate your applications can verify tokens against\n— the call you make to bring your own key, or to stage the next one before a\nrotation. A name already used in your organization is refused.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Cert].id": "Persisted fields",
		},
	})
	zip.Describe("POST /v1/iam/certs/delete", zip.Doc{
		Description: "Removes a signing certificate. Tokens signed with it can no longer be\nverified, so retire it only once nothing is still presenting them.",
	})
	zip.Describe("POST /v1/iam/certs/update", zip.Doc{
		Description: "Changes a signing certificate's settings. What it is called does not\nchange, and neither does when it was added.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Cert].id": "Persisted fields",
		},
	})
}
