// Code generated by zipdoc; DO NOT EDIT.

package teams

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/iam/teams/:name", zip.Doc{
		Description: "Removes a team. Everyone in it loses the access it carried; their\naccounts, and any other team they are in, are untouched.",
	})
	zip.Describe("GET /v1/iam/teams", zip.Doc{
		Description: "Returns your organization's teams, newest first — each a named set of\npeople that roles and permissions are granted to.\n\nYou see your own organization's teams and no one else's; which organization\nthat is comes from your credentials, not from the request.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Team].id": "Persisted fields",
		},
	})
	zip.Describe("GET /v1/iam/teams/:name", zip.Doc{
		Description: "Returns one team: who is in it.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Team].id": "Persisted fields",
		},
	})
	zip.Describe("POST /v1/iam/teams", zip.Doc{
		Description: "Makes a team — a named set of people that roles and permissions grant\nto. Granting to a team rather than to each person keeps access correct as\npeople come and go: add someone and they inherit what the team can do. A name\nalready used in your organization is refused.",
		Fields: map[string]string{
			"Input.name": "Name addresses the team on update and names it on create; every other\nfield is content and binds from the BODY, never the URL.",
			"Model[github.com/hanzoai/iam/pkg/schema.Team].id": "Persisted fields",
		},
	})
	zip.Describe("PUT /v1/iam/teams/:name", zip.Doc{
		Description: "Changes who is in a team. Access changes for\neveryone in it as soon as the write lands. The name and the created stamp do\nnot change.",
		Fields: map[string]string{
			"Input.name": "Name addresses the team on update and names it on create; every other\nfield is content and binds from the BODY, never the URL.",
			"Model[github.com/hanzoai/iam/pkg/schema.Team].id": "Persisted fields",
		},
	})
}
