appname = hanzo-iam
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = postgres
dataSourceName =
dbName =
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "hanzo"
socks5Proxy =
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameLowered = false
origin = https://hanzo.id
originFrontend = https://hanzo.id
staticBaseUrl = "https://cdn.hanzo.ai"
isDemoMode = false
batchSize = 100
enableErrorMask = true
enableGzip = true
inactiveTimeoutMinutes = 30
ldapServerPort = 389
ldapsCertId = ""
ldapsServerPort = 636
radiusServerPort = 1812
radiusDefaultOrganization = "hanzo"
radiusSecret = ${IAM_RADIUS_SECRET}
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"adapter":"console"}
initDataNewOnly = true
initDataFile = "./init_data.json"
frontendBaseDir = "./web"
kmsUrl = https://kms.hanzo.ai
kmsProjectSlug = hanzo-iam
kmsEnvironment = prod
