appname = hanzo-iam
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = sqlite
dataSourceName = file:data/iam.db?_journal_mode=WAL&_busy_timeout=5000&cache=shared
dbName = hanzo_iam
orgIsolation = sqlite
dataDir = data

tableNamePrefix =
showSql = true
redisEndpoint = localhost:6379
defaultStorageProvider =
isCloudIntranet = false
authState = "hanzo"
socks5Proxy =
verificationCodeTimeout = 10
initScore = 100
logPostOnly = true
isUsernameLowered = false
origin = http://localhost:8000
originFrontend = http://localhost:8000
staticBaseUrl = "https://cdn.hanzo.ai"
isDemoMode = false
batchSize = 100
enableErrorMask = false
enableGzip = true
inactiveTimeoutMinutes = 30
ldapServerPort = 389
ldapsCertId = ""
ldapsServerPort = 636
radiusServerPort = 1812
radiusDefaultOrganization = "hanzo"
radiusSecret = ${IAM_RADIUS_SECRET}
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"adapter":"console", "level":7}
initDataNewOnly = true
initDataFile = "./init_data.json"
frontendBaseDir = "./web"
