appname = iam
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
EnableGzip = true
EnableErrorsRender = false
driverName = sqlite
dataSourceName = file::memory:?cache=shared
tableNamePrefix =
dbName = iam_test
