appname = hanzo-iam
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = postgres
dataSourceName = user=hanzo password=${IAM_DB_PASSWORD} host=${IAM_DB_HOST:-postgres} port=5432 sslmode=require dbname=hanzo_iam
dbName = hanzo_iam
tableNamePrefix =
showSql = false
redisEndpoint = ${IAM_REDIS_HOST:-redis}:6379
defaultStorageProvider =
isCloudIntranet = false
authState = "hanzo"
socks5Proxy =
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameLowered = false
origin = https://hanzo.id
originFrontend = https://hanzo.id
staticBaseUrl = "https://cdn.hanzo.ai"
isDemoMode = false
batchSize = 100
enableErrorMask = true
enableGzip = true
inactiveTimeoutMinutes = 30
ldapServerPort = 389
ldapsCertId = ""
ldapsServerPort = 636
radiusServerPort = 1812
radiusDefaultOrganization = "hanzo"
radiusSecret = ${IAM_RADIUS_SECRET:-secret}
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"adapter":"file", "filename": "logs/hanzo-iam.log", "maxdays":99999, "perm":"0770"}
initDataNewOnly = false
initDataFile = "./init_data.json"
frontendBaseDir = "../iam"
