appname = iam
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
EnableGzip = true
EnableErrorsRender = false
driverName = sqlite
dataSourceName = file::memory:?cache=shared
tableNamePrefix =
dbName = iam_test
verificationCodeTimeout = 10
logConfig = {"adapter": "file", "filename": "logs/iam.log", "maxdays":99999, "perm":"0770"}
