// Code generated by zipdoc; DO NOT EDIT.

package resolve

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("GET /v1/iam/keys/org", zip.Doc{
		Description: "Answers which organization a PUBLISHABLE key belongs to — what a service of\nyours calls to attribute a request that arrived carrying a key shipped in a\nbrowser.\n\nIt names an organization and never a person. A key that is expired, secret\nrather than publishable, or simply unknown all answer with the same sentence,\nand with a `code` saying which of those it was. Only a confidential service\nthat already proved it may resolve keys at all ever reads that code — there is\nno anonymous caller here to probe for which keys exist — and telling it apart\nis what lets the holder be told to re-mint an expired key instead of hunting a\nconfiguration error.",
	})
	zip.Describe("GET /v1/iam/keys/principal", zip.Doc{
		Description: "Answers which account a SECRET key belongs to — what a gateway of yours calls\nto attribute and bill a request that arrived carrying an sk-.\n\nA publishable key resolves to nobody here, deliberately: it is safe to ship in\na browser precisely because it names an organization and never a person.\n\nTHE `msg` STAYS UNIFORM AND THE `code` SAYS WHY. Every unresolvable key answers\nthe same not-exist sentence, so nothing that reads the prose can tell a missing\nkey from a denied one. The machine-readable reason rides beside it because THE\nCAPABILITY ABOVE IS THE BOUNDARY, not the vagueness of this sentence: a caller\nthat reaches this line has already proven it is a confidential app holding\nCapKeyResolve, and such a caller can resolve any key it likes to a full\nprincipal. Telling it which refusal occurred discloses nothing it could not\nalready obtain, and withholding it is what made a revoked key\nindistinguishable from a deleted org for every human downstream. There is no\nanonymous reader of this envelope to oracle.",
	})
}
