// Code generated by zipdoc; DO NOT EDIT.

package scim

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/iam/scim/v2/Users/:owner/:name", zip.Doc{
		Description: "Deprovisions a person — how removing someone in your identity\nprovider removes their access here. Their sessions stop working immediately.\nTakes an administrator.",
	})
	zip.Describe("GET /v1/iam/scim/v2/ResourceTypes", zip.Doc{
		Description: "Returns the kinds of record this directory provisions and\nthe address of each, so your identity provider discovers them rather than\nhaving them configured by hand.",
	})
	zip.Describe("GET /v1/iam/scim/v2/ResourceTypes/:name", zip.Doc{
		Description: "Returns one provisionable record kind in full.",
	})
	zip.Describe("GET /v1/iam/scim/v2/Schemas", zip.Doc{
		Description: "Returns the attribute definitions this directory understands, so\nyour identity provider knows which fields it may send and what they mean\nbefore it sends any.",
	})
	zip.Describe("GET /v1/iam/scim/v2/Schemas/:id", zip.Doc{
		Description: "Returns one attribute definition in full.",
	})
	zip.Describe("GET /v1/iam/scim/v2/ServiceProviderConfig", zip.Doc{
		Description: "Tells your identity provider which parts of SCIM this\ndirectory supports, so it configures itself instead of you filling in a form.\n\nFiltering and partial updates are supported. Bulk operations, sorting and\nentity tags are not — an IdP that reads this will not attempt them.",
	})
	zip.Describe("GET /v1/iam/scim/v2/Users", zip.Doc{
		Description: "Returns the people in your organization to your identity provider,\nin the standard SCIM shape, so an IdP can reconcile its directory against\nours. Searchable by username or email address, and paged.\n\nReading the whole list takes an administrator; an ordinary person is refused.",
	})
	zip.Describe("GET /v1/iam/scim/v2/Users/:owner/:name", zip.Doc{
		Description: "Returns one person in the standard SCIM shape. An administrator may\nread anyone in the organization; everyone else may read only themselves.",
	})
	zip.Describe("PATCH /v1/iam/scim/v2/Users/:owner/:name", zip.Doc{
		Description: "Applies a partial change from your identity provider — one attribute\nmoved, not the whole record resent.\n\nThe change is applied onto the person as they currently are, so everything you\ndid not mention keeps its value, including the parts SCIM does not describe.",
	})
	zip.Describe("POST /v1/iam/scim/v2/Users", zip.Doc{
		Description: "Provisions a person from your identity provider — how a new hire\ngets an account here automatically when they are added over there.\n\nTakes an administrator. Making someone an administrator takes more than that,\nso an IdP integration cannot escalate anyone by setting a flag.",
	})
	zip.Describe("PUT /v1/iam/scim/v2/Users/:owner/:name", zip.Doc{
		Description: "Overwrites a person's SCIM attributes with what your identity\nprovider sends — how a change made there lands here.\n\nOnly the attributes SCIM describes are replaced. Anything the standard does not\ncover — their multi-factor enrolment above all — survives untouched, so a\nroutine sync from your IdP can never quietly strip someone's second factor or\nbring a deleted account back.",
	})
}
