// Code generated by zipdoc; DO NOT EDIT.

package sessions

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("POST /v1/iam/sessions/create", zip.Doc{
		Description: "Records a sign-in. Signing in again from another browser adds to the\nsession rather than replacing it, so one person can be signed in from a laptop\nand a phone at once.\n\nAsk for an exclusive sign-in and the opposite holds: the new sign-in is the only\none left and every other browser is signed out. That is the setting to use when\none person may hold only one live session at a time.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Session].id": "Persisted fields",
			"Session.applicationDisplayName":                      "ApplicationDisplayName is the human label of the Application this session\nis against, and HomepageUrl is where \"jump back in\" goes. Both are\nprojections resolved at read time from the application row (the same\norm:\"-\" enrichment pattern ProviderItem.Provider uses), never stored —\nstoring them would let a renamed application go stale in every session row.",
			"Session.exclusiveSignin":                             "ExclusiveSignin is a transient control flag (v1 xorm:\"-\"): a caller sets\nit on a create to collapse SessionId down to the single incoming cookie\ninstead of appending. It is never stored — a persisted session always\ncarries it false, so orm:\"-\" keeps it off the column backends and\nomitempty keeps it out of the SQLite JSON blob.",
			"Session.seen":                                        "Seen is what we OBSERVED about each cookie id — the device it rides in,\nwhen it was issued, when it was last presented. It is deliberately a\nseparate value from SessionId rather than a richer element type, because\nthe two answer different questions with different authorities:\nSessionId is the authority on LIVENESS (a sid absent from it is revoked,\nfull stop), Seen is an observation log that may lag, may be empty for a\nsession issued before this field existed, and may never gate a decision.\nBraiding them would make a telemetry write failure able to revoke a live\nsession. Readers JOIN the two — a Seen entry for a sid that is no longer\nin SessionId is stale and is dropped on the next write.",
		},
	})
	zip.Describe("POST /v1/iam/sessions/delete", zip.Doc{
		Description: "Signs a person out of one application — the session ends and every\nbrowser carrying it stops being authenticated.\n\nA session that is already gone reports that nothing was deleted rather than an\nerror, so the call is safe to repeat.",
	})
	zip.Describe("POST /v1/iam/sessions/get", zip.Doc{
		Description: "Returns one person's session in one application — when it began and which\nbrowsers or devices are still carrying it.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Session].id": "Persisted fields",
			"Session.applicationDisplayName":                      "ApplicationDisplayName is the human label of the Application this session\nis against, and HomepageUrl is where \"jump back in\" goes. Both are\nprojections resolved at read time from the application row (the same\norm:\"-\" enrichment pattern ProviderItem.Provider uses), never stored —\nstoring them would let a renamed application go stale in every session row.",
			"Session.exclusiveSignin":                             "ExclusiveSignin is a transient control flag (v1 xorm:\"-\"): a caller sets\nit on a create to collapse SessionId down to the single incoming cookie\ninstead of appending. It is never stored — a persisted session always\ncarries it false, so orm:\"-\" keeps it off the column backends and\nomitempty keeps it out of the SQLite JSON blob.",
			"Session.seen":                                        "Seen is what we OBSERVED about each cookie id — the device it rides in,\nwhen it was issued, when it was last presented. It is deliberately a\nseparate value from SessionId rather than a richer element type, because\nthe two answer different questions with different authorities:\nSessionId is the authority on LIVENESS (a sid absent from it is revoked,\nfull stop), Seen is an observation log that may lag, may be empty for a\nsession issued before this field existed, and may never gate a decision.\nBraiding them would make a telemetry write failure able to revoke a live\nsession. Readers JOIN the two — a Seen entry for a sid that is no longer\nin SessionId is stale and is dropped on the next write.",
		},
	})
	zip.Describe("POST /v1/iam/sessions/list", zip.Doc{
		Description: "Returns who is currently signed in to your organization, newest first, and\ncan be narrowed to one person or one application. It is what you read before\nsigning someone out.\n\nEach session comes back describing itself: the application's human name and\nhomepage, and per browser cookie the device it rides in, when it started and\nwhen it was last used. That is the ONE session read — the account page derives\n\"last used app\" from it rather than from a second table that could disagree\nwith which sessions are actually live.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Session].id": "Persisted fields",
			"Session.applicationDisplayName":                      "ApplicationDisplayName is the human label of the Application this session\nis against, and HomepageUrl is where \"jump back in\" goes. Both are\nprojections resolved at read time from the application row (the same\norm:\"-\" enrichment pattern ProviderItem.Provider uses), never stored —\nstoring them would let a renamed application go stale in every session row.",
			"Session.exclusiveSignin":                             "ExclusiveSignin is a transient control flag (v1 xorm:\"-\"): a caller sets\nit on a create to collapse SessionId down to the single incoming cookie\ninstead of appending. It is never stored — a persisted session always\ncarries it false, so orm:\"-\" keeps it off the column backends and\nomitempty keeps it out of the SQLite JSON blob.",
			"Session.seen":                                        "Seen is what we OBSERVED about each cookie id — the device it rides in,\nwhen it was issued, when it was last presented. It is deliberately a\nseparate value from SessionId rather than a richer element type, because\nthe two answer different questions with different authorities:\nSessionId is the authority on LIVENESS (a sid absent from it is revoked,\nfull stop), Seen is an observation log that may lag, may be empty for a\nsession issued before this field existed, and may never gate a decision.\nBraiding them would make a telemetry write failure able to revoke a live\nsession. Readers JOIN the two — a Seen entry for a sid that is no longer\nin SessionId is stale and is dropped on the next write.",
		},
	})
	zip.Describe("POST /v1/iam/sessions/update", zip.Doc{
		Description: "Replaces the set of browsers a session covers — signing out the ones you\nleave off while the session itself stays live. A session that does not exist is\nreported as missing rather than created.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Session].id": "Persisted fields",
			"Session.applicationDisplayName":                      "ApplicationDisplayName is the human label of the Application this session\nis against, and HomepageUrl is where \"jump back in\" goes. Both are\nprojections resolved at read time from the application row (the same\norm:\"-\" enrichment pattern ProviderItem.Provider uses), never stored —\nstoring them would let a renamed application go stale in every session row.",
			"Session.exclusiveSignin":                             "ExclusiveSignin is a transient control flag (v1 xorm:\"-\"): a caller sets\nit on a create to collapse SessionId down to the single incoming cookie\ninstead of appending. It is never stored — a persisted session always\ncarries it false, so orm:\"-\" keeps it off the column backends and\nomitempty keeps it out of the SQLite JSON blob.",
			"Session.seen":                                        "Seen is what we OBSERVED about each cookie id — the device it rides in,\nwhen it was issued, when it was last presented. It is deliberately a\nseparate value from SessionId rather than a richer element type, because\nthe two answer different questions with different authorities:\nSessionId is the authority on LIVENESS (a sid absent from it is revoked,\nfull stop), Seen is an observation log that may lag, may be empty for a\nsession issued before this field existed, and may never gate a decision.\nBraiding them would make a telemetry write failure able to revoke a live\nsession. Readers JOIN the two — a Seen entry for a sid that is no longer\nin SessionId is stale and is dropped on the next write.",
		},
	})
}
