// Code generated by zipdoc; DO NOT EDIT.

package memberships

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/hanzoai/iam/internal/memberships GET /v1/iam/memberships", zip.Doc{
		Description: "Answers either question about who belongs where: which organizations one\nperson can act in, or who can act in one organization.\n\nBoth are org-scoped: a non-SuperAdmin may read the roster of an org it belongs\nto, or the tenancy of a person whose account it administers, and nothing else.\nThe bound comes from the verified credential via principal.ScopeRead, so a\nrequest parameter can never widen it — a membership row names who may act and\nspend in an org, so a roster read by a stranger is a customer roster leak.",
		Fields: map[string]string{
			"Response.code": "Code is a STABLE machine-readable reason, where the human `msg` is\ndeliberately generic. `msg` is prose for a person and several distinct causes\nlegitimately share one sentence; a caller that must BRANCH on the cause — or\ntell its own user which of them happened — cannot parse prose. Optional, so\nevery existing envelope is byte-identical and no SDK changes.",
			"lookup.org":    "Org is an organization — who may act in it.",
			"lookup.user":   "User is \"<homeOrg>/<username>\" — which organizations that identity may act in.",
		},
	})
	zip.Describe("github.com/hanzoai/iam/internal/memberships POST /v1/iam/delete-membership", zip.Doc{
		Description: "Takes away a person's or an application's right to act in an\norganization. Their account survives; what ends is their access to that\norganization. Revoking a membership that is already gone reports that nothing\nwas removed rather than failing, so a retry is safe. It is the mirror of ensure\nand takes the SAME gate: a SuperAdmin, an admin of the org itself, or an\norg-admin-capable confidential client — and for an owner, only an owner or a\nSuperAdmin. The last owner is never removed.",
	})
	zip.Describe("github.com/hanzoai/iam/internal/memberships POST /v1/iam/memberships", zip.Doc{
		Description: "Lets a person or an application act in an organization. It is the grant\nbehind \"add someone to the team\", and it is safe to repeat — granting a\nmembership that already exists changes nothing. Granting membership IS the\norg's authority to give, so it takes the same gate a write to that org's own\nregistry row takes: a SuperAdmin, an admin of the org itself, or an\norg-admin-capable confidential client. The owner role is given only by an\nowner or a SuperAdmin.",
	})
	zip.Describe("github.com/hanzoai/iam/internal/memberships PUT /v1/iam/memberships", zip.Doc{
		Description: "Moves a person between an organization's roles: owner, admin and\nmember. An owner or a SuperAdmin moves anyone into or out of the owner role;\nan admin moves people between admin and member. The last owner cannot be\nmoved out of it — make someone else an owner first — so handing an org over\nis two updates: the new owner in, then the old one out.",
	})
}
