// Code generated by zipdoc; DO NOT EDIT.

package memberships

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/hanzoai/iam/internal/memberships GET /v1/iam/memberships", zip.Doc{
		Description: "Answers either question about who belongs where: which organizations one\nperson can act in, or who can act in one organization.\n\nBoth are org-scoped: a non-SuperAdmin may read the roster of an org it belongs\nto, or the tenancy of a person whose account it administers, and nothing else.\nThe bound comes from the verified credential via principal.ScopeRead, so a\nrequest parameter can never widen it — a membership row names who may act and\nspend in an org, so a roster read by a stranger is a customer roster leak.",
		Fields: map[string]string{
			"Response.code": "Code is a STABLE machine-readable reason, where the human `msg` is\ndeliberately generic. `msg` is prose for a person and several distinct causes\nlegitimately share one sentence; a caller that must BRANCH on the cause — or\ntell its own user which of them happened — cannot parse prose. Optional, so\nevery existing envelope is byte-identical and no SDK changes.",
			"lookup.org":    "Org is an organization — who may act in it.",
			"lookup.user":   "User is \"<homeOrg>/<username>\" — which organizations that identity may act in.",
		},
	})
	zip.Describe("github.com/hanzoai/iam/internal/memberships POST /v1/iam/delete-membership", zip.Doc{
		Description: "Takes away a person's or an application's right to act in an\norganization. Their account survives; what ends is their access to that\norganization. Revoking a membership that is already gone reports that nothing\nwas removed rather than failing, so a retry is safe. It is the mirror of ensure and takes the SAME gate:\nrevoking membership is the org's authority to give or take, so a SuperAdmin, an\nadmin of the org itself, or an org-admin-capable confidential client. Idempotent\nthrough the store — deleting an absent membership reports removed=false, never an\nerror — so a retried revoke is safe.",
	})
	zip.Describe("github.com/hanzoai/iam/internal/memberships POST /v1/iam/memberships", zip.Doc{
		Description: "Lets a person or an application act in an organization. It is the grant\nbehind \"add someone to the team\", and it is safe to repeat — granting a\nmembership that already exists changes nothing. Granting membership IS the org's authority to give, so it takes the\nsame gate a write to that org's own registry row takes: a SuperAdmin, an admin\nof the org itself, or an org-admin-capable confidential client. One rule, one\nplace (internal/authz).",
	})
}
