// Code generated by zipdoc; DO NOT EDIT.

package invitations

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/hanzoai/iam/internal/invitations DELETE /v1/iam/invitations/:owner/:name", zip.Doc{
		Description: "Withdraws an invitation. It stops being redeemable at once; anyone who\nalready joined through it keeps their account.",
	})
	zip.Describe("github.com/hanzoai/iam/internal/invitations GET /v1/iam/invitations", zip.Doc{
		Description: "Returns your organization's invitations, newest first — who has\nbeen asked to join, on what terms, and how many seats each invitation still\nhas left.\n\nYou see the invitations of the organization your credentials run, and no one\nelse's: your own, or one you own or administer.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Invitation].id": "Persisted fields",
		},
	})
	zip.Describe("github.com/hanzoai/iam/internal/invitations GET /v1/iam/invitations/:owner/:name", zip.Doc{
		Description: "Returns one invitation: who it is for, what it grants on acceptance, and\nwhen it expires.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Invitation].id": "Persisted fields",
		},
	})
	zip.Describe("github.com/hanzoai/iam/internal/invitations POST /v1/iam/invitations", zip.Doc{
		Description: "Issues an invitation to join your organization — the code or link a new\nmember redeems, with the role they arrive holding and the date it stops\nworking. A name already used in the organization is refused.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Invitation].id": "Persisted fields",
		},
	})
	zip.Describe("github.com/hanzoai/iam/internal/invitations PUT /v1/iam/invitations/:owner/:name", zip.Doc{
		Description: "Changes an invitation's terms — the role it grants, how many may redeem\nit, or when it expires. What it is called does not change.",
		Fields: map[string]string{
			"Model[github.com/hanzoai/iam/pkg/schema.Invitation].id": "Persisted fields",
		},
	})
}
